
//! Autogenerated weights for pallet_domains
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-02-14, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
    // ./scripts/../target/release/subsocial-collator
    // benchmark
    // pallet
    // --chain
    // dev
    // --execution
    // wasm
    // --wasm-execution
    // Compiled
    // --pallet
    // pallet_domains
    // --extrinsic
    // *
    // --steps
    // 50
    // --repeat
    // 20
    // --heap-pages
    // 4096
    // --output
    // pallets/domains/src/weights.rs
    // --template
    // ./.maintain/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(non_snake_case)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_domains.
pub trait WeightInfo {
    fn register_domain() -> Weight;
    fn force_register_domain() -> Weight;
    fn set_inner_value() -> Weight;
    fn force_set_inner_value() -> Weight;
    fn set_outer_value() -> Weight;
    fn set_domain_content() -> Weight;
    fn reserve_words(s: u32, ) -> Weight;
    fn support_tlds(s: u32, ) -> Weight;
}

/// Weights for pallet_domains using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
        impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
            // Storage: Domains DomainsByOwner (r:1 w:1)
            // Storage: Domains ReservedWords (r:1 w:0)
            // Storage: Domains RegisteredDomains (r:1 w:1)
            // Storage: Timestamp Now (r:1 w:0)
        fn register_domain() -> Weight {
        // Minimum execution time: 37_000 nanoseconds.
        Weight::from_ref_time(64_360_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(2))
        }
            // Storage: Domains DomainsByOwner (r:1 w:1)
            // Storage: Domains RegisteredDomains (r:1 w:1)
            // Storage: Timestamp Now (r:1 w:0)
        fn force_register_domain() -> Weight {
        // Minimum execution time: 24_000 nanoseconds.
        Weight::from_ref_time(39_812_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(2))
        }
            // Storage: Domains RegisteredDomains (r:1 w:1)
            // Storage: Domains DomainByInnerValue (r:0 w:2)
        fn set_inner_value() -> Weight {
        // Minimum execution time: 24_000 nanoseconds.
        Weight::from_ref_time(37_599_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(3))
        }
            // Storage: Domains RegisteredDomains (r:1 w:1)
            // Storage: Domains DomainByInnerValue (r:0 w:2)
        fn force_set_inner_value() -> Weight {
        // Minimum execution time: 24_000 nanoseconds.
        Weight::from_ref_time(36_287_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(3))
        }
            // Storage: Domains RegisteredDomains (r:1 w:1)
        fn set_outer_value() -> Weight {
        // Minimum execution time: 31_000 nanoseconds.
        Weight::from_ref_time(51_741_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
        }
            // Storage: Domains RegisteredDomains (r:1 w:1)
        fn set_domain_content() -> Weight {
        // Minimum execution time: 20_000 nanoseconds.
        Weight::from_ref_time(30_119_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
        }
            // Storage: Domains ReservedWords (r:0 w:1)
            /// The range of component `s` is `[1, 2860]`.
        fn reserve_words(s: u32, ) -> Weight {
        // Minimum execution time: 13_000 nanoseconds.
        Weight::from_ref_time(112_751_000)
            // Standard Error: 5_361
            .saturating_add(Weight::from_ref_time(1_646_463).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().writes(313))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
        }
            // Storage: Domains SupportedTlds (r:0 w:1)
            /// The range of component `s` is `[1, 2860]`.
        fn support_tlds(s: u32, ) -> Weight {
        // Minimum execution time: 13_000 nanoseconds.
        Weight::from_ref_time(75_703_000)
            // Standard Error: 6_827
            .saturating_add(Weight::from_ref_time(1_732_820).saturating_mul(s.into()))
            .saturating_add(T::DbWeight::get().writes(313))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(s.into())))
        }
    }

    // For backwards compatibility and tests
    impl WeightInfo for () {
            // Storage: Domains DomainsByOwner (r:1 w:1)
            // Storage: Domains ReservedWords (r:1 w:0)
            // Storage: Domains RegisteredDomains (r:1 w:1)
            // Storage: Timestamp Now (r:1 w:0)
        fn register_domain() -> Weight {
        // Minimum execution time: 37_000 nanoseconds.
        Weight::from_ref_time(64_360_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(2))
        }
            // Storage: Domains DomainsByOwner (r:1 w:1)
            // Storage: Domains RegisteredDomains (r:1 w:1)
            // Storage: Timestamp Now (r:1 w:0)
        fn force_register_domain() -> Weight {
        // Minimum execution time: 24_000 nanoseconds.
        Weight::from_ref_time(39_812_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(2))
        }
            // Storage: Domains RegisteredDomains (r:1 w:1)
            // Storage: Domains DomainByInnerValue (r:0 w:2)
        fn set_inner_value() -> Weight {
        // Minimum execution time: 24_000 nanoseconds.
        Weight::from_ref_time(37_599_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(3))
        }
            // Storage: Domains RegisteredDomains (r:1 w:1)
            // Storage: Domains DomainByInnerValue (r:0 w:2)
        fn force_set_inner_value() -> Weight {
        // Minimum execution time: 24_000 nanoseconds.
        Weight::from_ref_time(36_287_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(3))
        }
            // Storage: Domains RegisteredDomains (r:1 w:1)
        fn set_outer_value() -> Weight {
        // Minimum execution time: 31_000 nanoseconds.
        Weight::from_ref_time(51_741_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
        }
            // Storage: Domains RegisteredDomains (r:1 w:1)
        fn set_domain_content() -> Weight {
        // Minimum execution time: 20_000 nanoseconds.
        Weight::from_ref_time(30_119_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
        }
            // Storage: Domains ReservedWords (r:0 w:1)
            /// The range of component `s` is `[1, 2860]`.
        fn reserve_words(s: u32, ) -> Weight {
        // Minimum execution time: 13_000 nanoseconds.
        Weight::from_ref_time(112_751_000)
            // Standard Error: 5_361
            .saturating_add(Weight::from_ref_time(1_646_463).saturating_mul(s.into()))
            .saturating_add(RocksDbWeight::get().writes(313))
            .saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(s.into())))
        }
            // Storage: Domains SupportedTlds (r:0 w:1)
            /// The range of component `s` is `[1, 2860]`.
        fn support_tlds(s: u32, ) -> Weight {
        // Minimum execution time: 13_000 nanoseconds.
        Weight::from_ref_time(75_703_000)
            // Standard Error: 6_827
            .saturating_add(Weight::from_ref_time(1_732_820).saturating_mul(s.into()))
            .saturating_add(RocksDbWeight::get().writes(313))
            .saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(s.into())))
        }
    }
