
//! Autogenerated weights for pallet_evm_addresses
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-05, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `benchmarks-ci`, CPU: `Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./scripts/../target/release/subsocial-collator
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet
// pallet_evm_addresses
// --extrinsic
// *
// --execution=wasm
// --wasm-execution=Compiled
// --heap-pages=4096
// --output=./pallets/evm-addresses/src/weights.rs
// --template=./.maintain/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(non_snake_case)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_evm_addresses.
pub trait WeightInfo {
    fn link_evm_address() -> Weight;
    fn unlink_evm_address() -> Weight;
}

/// Weights for pallet_evm_addresses using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: System Account (r:1 w:0)
    /// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    /// Storage: EvmAddresses AccountsByEvmAddress (r:1 w:1)
    /// Proof Skipped: EvmAddresses AccountsByEvmAddress (max_values: None, max_size: None, mode: Measured)
    /// Storage: EvmAddresses EvmAddressByAccount (r:0 w:1)
    /// Proof Skipped: EvmAddresses EvmAddressByAccount (max_values: None, max_size: None, mode: Measured)
    fn link_evm_address() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `45`
        //  Estimated: `7148`
        // Minimum execution time: 76_658_000 picoseconds.
        Weight::from_parts(77_854_000, 7148)
            .saturating_add(T::DbWeight::get().reads(2_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: EvmAddresses AccountsByEvmAddress (r:1 w:1)
    /// Proof Skipped: EvmAddresses AccountsByEvmAddress (max_values: None, max_size: None, mode: Measured)
    /// Storage: EvmAddresses EvmAddressByAccount (r:0 w:1)
    /// Proof Skipped: EvmAddresses EvmAddressByAccount (max_values: None, max_size: None, mode: Measured)
    fn unlink_evm_address() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `135`
        //  Estimated: `3735`
        // Minimum execution time: 24_226_000 picoseconds.
        Weight::from_parts(24_833_000, 3735)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    /// Storage: System Account (r:1 w:0)
    /// Proof: System Account (max_values: None, max_size: Some(128), added: 2603, mode: MaxEncodedLen)
    /// Storage: EvmAddresses AccountsByEvmAddress (r:1 w:1)
    /// Proof Skipped: EvmAddresses AccountsByEvmAddress (max_values: None, max_size: None, mode: Measured)
    /// Storage: EvmAddresses EvmAddressByAccount (r:0 w:1)
    /// Proof Skipped: EvmAddresses EvmAddressByAccount (max_values: None, max_size: None, mode: Measured)
    fn link_evm_address() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `45`
        //  Estimated: `7148`
        // Minimum execution time: 76_658_000 picoseconds.
        Weight::from_parts(77_854_000, 7148)
            .saturating_add(RocksDbWeight::get().reads(2_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
    /// Storage: EvmAddresses AccountsByEvmAddress (r:1 w:1)
    /// Proof Skipped: EvmAddresses AccountsByEvmAddress (max_values: None, max_size: None, mode: Measured)
    /// Storage: EvmAddresses EvmAddressByAccount (r:0 w:1)
    /// Proof Skipped: EvmAddresses EvmAddressByAccount (max_values: None, max_size: None, mode: Measured)
    fn unlink_evm_address() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `135`
        //  Estimated: `3735`
        // Minimum execution time: 24_226_000 picoseconds.
        Weight::from_parts(24_833_000, 3735)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(2_u64))
    }
}