
//! Autogenerated weights for pallet_evm_addresses
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-05-29, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `Tarek-M1-Pro.local`, CPU: `<UNKNOWN>`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
    // ./scripts/../target/release/subsocial-collator
    // benchmark
    // pallet
    // --chain
    // dev
    // --execution
    // wasm
    // --wasm-execution
    // Compiled
    // --pallet
    // pallet_evm_addresses
    // --extrinsic
    // *
    // --steps
    // 50
    // --repeat
    // 20
    // --heap-pages
    // 4096
    // --output
    // ./pallets/evm-addresses/src/weights.rs
    // --template
    // ./.maintain/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(non_snake_case)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_evm_addresses.
pub trait WeightInfo {
    fn link_evm_address() -> Weight;
}

/// Weights for pallet_evm_addresses using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
        impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
            // Storage: System Account (r:1 w:0)
            // Storage: EvmAddresses AccountsByEvmAddress (r:1 w:1)
            // Storage: EvmAddresses EvmAddressByAccount (r:0 w:1)
        fn link_evm_address() -> Weight {
        // Minimum execution time: 57_000 nanoseconds.
        Weight::from_ref_time(59_000_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(2))
        }
    }

    // For backwards compatibility and tests
    impl WeightInfo for () {
            // Storage: System Account (r:1 w:0)
            // Storage: EvmAddresses AccountsByEvmAddress (r:1 w:1)
            // Storage: EvmAddresses EvmAddressByAccount (r:0 w:1)
        fn link_evm_address() -> Weight {
        // Minimum execution time: 57_000 nanoseconds.
        Weight::from_ref_time(59_000_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(2))
        }
    }
