// Copyright (C) DAPPFORCE PTE. LTD.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0.
//
// Full notice is available at https://github.com/dappforce/subsocial-parachain/blob/main/COPYRIGHT
// Full license is available at https://github.com/dappforce/subsocial-parachain/blob/main/LICENSE


//! Autogenerated weights for pallet_posts
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-30, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `benchmarks-ci`, CPU: `Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./scripts/../target/release/subsocial-collator
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet
// pallet_posts
// --extrinsic
// *
// --execution=wasm
// --wasm-execution=Compiled
// --heap-pages=4096
// --output=/root/weights.rs
// --template=./.maintain/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(non_snake_case)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_posts.
pub trait WeightInfo {
    fn create_post__regular() -> Weight;
    fn create_post__shared() -> Weight;
    fn create_post__comment() -> Weight;
    fn update_post() -> Weight;
    fn move_post() -> Weight;
}

/// Weights for pallet_posts using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: Posts NextPostId (r:1 w:1)
    /// Proof Skipped: Posts NextPostId (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: Timestamp Now (r:1 w:0)
    /// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    /// Storage: Spaces SpaceById (r:1 w:0)
    /// Proof Skipped: Spaces SpaceById (max_values: None, max_size: None, mode: Measured)
    /// Storage: SpaceFollows SpaceFollowedByAccount (r:1 w:0)
    /// Proof Skipped: SpaceFollows SpaceFollowedByAccount (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts PostIdsBySpaceId (r:1 w:1)
    /// Proof Skipped: Posts PostIdsBySpaceId (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts PostById (r:0 w:1)
    /// Proof Skipped: Posts PostById (max_values: None, max_size: None, mode: Measured)
    fn create_post__regular() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1566`
        //  Estimated: `21203`
        // Minimum execution time: 50_158_000 picoseconds.
        Weight::from_parts(51_385_000, 21203)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: Posts NextPostId (r:1 w:1)
    /// Proof Skipped: Posts NextPostId (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: Timestamp Now (r:1 w:0)
    /// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    /// Storage: Spaces SpaceById (r:1 w:0)
    /// Proof Skipped: Spaces SpaceById (max_values: None, max_size: None, mode: Measured)
    /// Storage: SpaceFollows SpaceFollowedByAccount (r:1 w:0)
    /// Proof Skipped: SpaceFollows SpaceFollowedByAccount (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts PostById (r:1 w:1)
    /// Proof Skipped: Posts PostById (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts SharedPostIdsByOriginalPostId (r:1 w:1)
    /// Proof Skipped: Posts SharedPostIdsByOriginalPostId (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts PostIdsBySpaceId (r:1 w:1)
    /// Proof Skipped: Posts PostIdsBySpaceId (max_values: None, max_size: None, mode: Measured)
    fn create_post__shared() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1789`
        //  Estimated: `31037`
        // Minimum execution time: 70_387_000 picoseconds.
        Weight::from_parts(72_891_000, 31037)
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: Posts NextPostId (r:1 w:1)
    /// Proof Skipped: Posts NextPostId (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: Timestamp Now (r:1 w:0)
    /// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    /// Storage: Posts PostById (r:2 w:1)
    /// Proof Skipped: Posts PostById (max_values: None, max_size: None, mode: Measured)
    /// Storage: Spaces SpaceById (r:1 w:0)
    /// Proof Skipped: Spaces SpaceById (max_values: None, max_size: None, mode: Measured)
    /// Storage: SpaceFollows SpaceFollowedByAccount (r:1 w:0)
    /// Proof Skipped: SpaceFollows SpaceFollowedByAccount (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts ReplyIdsByPostId (r:1 w:1)
    /// Proof Skipped: Posts ReplyIdsByPostId (max_values: None, max_size: None, mode: Measured)
    fn create_post__comment() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1963`
        //  Estimated: `29128`
        // Minimum execution time: 72_394_000 picoseconds.
        Weight::from_parts(74_150_000, 29128)
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: Posts PostById (r:2 w:1)
    /// Proof Skipped: Posts PostById (max_values: None, max_size: None, mode: Measured)
    /// Storage: Spaces SpaceById (r:1 w:0)
    /// Proof Skipped: Spaces SpaceById (max_values: None, max_size: None, mode: Measured)
    /// Storage: SpaceFollows SpaceFollowedByAccount (r:1 w:0)
    /// Proof Skipped: SpaceFollows SpaceFollowedByAccount (max_values: None, max_size: None, mode: Measured)
    fn update_post() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1874`
        //  Estimated: `18492`
        // Minimum execution time: 50_055_000 picoseconds.
        Weight::from_parts(52_079_000, 18492)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: Posts PostById (r:1 w:1)
    /// Proof Skipped: Posts PostById (max_values: None, max_size: None, mode: Measured)
    /// Storage: Spaces SpaceById (r:2 w:0)
    /// Proof Skipped: Spaces SpaceById (max_values: None, max_size: None, mode: Measured)
    /// Storage: SpaceFollows SpaceFollowedByAccount (r:2 w:0)
    /// Proof Skipped: SpaceFollows SpaceFollowedByAccount (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts PostIdsBySpaceId (r:2 w:2)
    /// Proof Skipped: Posts PostIdsBySpaceId (max_values: None, max_size: None, mode: Measured)
    fn move_post() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `2466`
        //  Estimated: `31149`
        // Minimum execution time: 65_086_000 picoseconds.
        Weight::from_parts(66_392_000, 31149)
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    /// Storage: Posts NextPostId (r:1 w:1)
    /// Proof Skipped: Posts NextPostId (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: Timestamp Now (r:1 w:0)
    /// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    /// Storage: Spaces SpaceById (r:1 w:0)
    /// Proof Skipped: Spaces SpaceById (max_values: None, max_size: None, mode: Measured)
    /// Storage: SpaceFollows SpaceFollowedByAccount (r:1 w:0)
    /// Proof Skipped: SpaceFollows SpaceFollowedByAccount (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts PostIdsBySpaceId (r:1 w:1)
    /// Proof Skipped: Posts PostIdsBySpaceId (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts PostById (r:0 w:1)
    /// Proof Skipped: Posts PostById (max_values: None, max_size: None, mode: Measured)
    fn create_post__regular() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1566`
        //  Estimated: `21203`
        // Minimum execution time: 50_158_000 picoseconds.
        Weight::from_parts(51_385_000, 21203)
            .saturating_add(RocksDbWeight::get().reads(5_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    /// Storage: Posts NextPostId (r:1 w:1)
    /// Proof Skipped: Posts NextPostId (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: Timestamp Now (r:1 w:0)
    /// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    /// Storage: Spaces SpaceById (r:1 w:0)
    /// Proof Skipped: Spaces SpaceById (max_values: None, max_size: None, mode: Measured)
    /// Storage: SpaceFollows SpaceFollowedByAccount (r:1 w:0)
    /// Proof Skipped: SpaceFollows SpaceFollowedByAccount (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts PostById (r:1 w:1)
    /// Proof Skipped: Posts PostById (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts SharedPostIdsByOriginalPostId (r:1 w:1)
    /// Proof Skipped: Posts SharedPostIdsByOriginalPostId (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts PostIdsBySpaceId (r:1 w:1)
    /// Proof Skipped: Posts PostIdsBySpaceId (max_values: None, max_size: None, mode: Measured)
    fn create_post__shared() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1789`
        //  Estimated: `31037`
        // Minimum execution time: 70_387_000 picoseconds.
        Weight::from_parts(72_891_000, 31037)
            .saturating_add(RocksDbWeight::get().reads(7_u64))
            .saturating_add(RocksDbWeight::get().writes(4_u64))
    }
    /// Storage: Posts NextPostId (r:1 w:1)
    /// Proof Skipped: Posts NextPostId (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: Timestamp Now (r:1 w:0)
    /// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    /// Storage: Posts PostById (r:2 w:1)
    /// Proof Skipped: Posts PostById (max_values: None, max_size: None, mode: Measured)
    /// Storage: Spaces SpaceById (r:1 w:0)
    /// Proof Skipped: Spaces SpaceById (max_values: None, max_size: None, mode: Measured)
    /// Storage: SpaceFollows SpaceFollowedByAccount (r:1 w:0)
    /// Proof Skipped: SpaceFollows SpaceFollowedByAccount (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts ReplyIdsByPostId (r:1 w:1)
    /// Proof Skipped: Posts ReplyIdsByPostId (max_values: None, max_size: None, mode: Measured)
    fn create_post__comment() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1963`
        //  Estimated: `29128`
        // Minimum execution time: 72_394_000 picoseconds.
        Weight::from_parts(74_150_000, 29128)
            .saturating_add(RocksDbWeight::get().reads(7_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
    /// Storage: Posts PostById (r:2 w:1)
    /// Proof Skipped: Posts PostById (max_values: None, max_size: None, mode: Measured)
    /// Storage: Spaces SpaceById (r:1 w:0)
    /// Proof Skipped: Spaces SpaceById (max_values: None, max_size: None, mode: Measured)
    /// Storage: SpaceFollows SpaceFollowedByAccount (r:1 w:0)
    /// Proof Skipped: SpaceFollows SpaceFollowedByAccount (max_values: None, max_size: None, mode: Measured)
    fn update_post() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1874`
        //  Estimated: `18492`
        // Minimum execution time: 50_055_000 picoseconds.
        Weight::from_parts(52_079_000, 18492)
            .saturating_add(RocksDbWeight::get().reads(4_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    /// Storage: Posts PostById (r:1 w:1)
    /// Proof Skipped: Posts PostById (max_values: None, max_size: None, mode: Measured)
    /// Storage: Spaces SpaceById (r:2 w:0)
    /// Proof Skipped: Spaces SpaceById (max_values: None, max_size: None, mode: Measured)
    /// Storage: SpaceFollows SpaceFollowedByAccount (r:2 w:0)
    /// Proof Skipped: SpaceFollows SpaceFollowedByAccount (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts PostIdsBySpaceId (r:2 w:2)
    /// Proof Skipped: Posts PostIdsBySpaceId (max_values: None, max_size: None, mode: Measured)
    fn move_post() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `2466`
        //  Estimated: `31149`
        // Minimum execution time: 65_086_000 picoseconds.
        Weight::from_parts(66_392_000, 31149)
            .saturating_add(RocksDbWeight::get().reads(7_u64))
            .saturating_add(RocksDbWeight::get().writes(3_u64))
    }
}