name: Feature Request
description: Submit your requests and suggestions to improve!
body:
  - type: checkboxes
    id: terms
    attributes:
      label: Is there an existing issue?
      description: Please search to see if an issue already exists and leave a comment that you also experienced this issue or add your specifics that are related to an existing issue.
      options:
        - label: I have searched the existing issues
          required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Please give precedence as to what lead you to file this issue.
    validations:
      required: true

  - type: textarea
    id: request
    attributes:
      label: Request
      description: Please describe what is needed.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Solution
      description: Please describe what a solution could be.
    validations:
      required: false

  - type: dropdown
    id: help
    attributes:
      label: Are you willing to help with this request?
      options:
        - Yes!
        - No.
        - Maybe (please elaborate above)
    validations:
      required: true
