// Copyright (C) DAPPFORCE PTE. LTD.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0.
//
// Full notice is available at https://github.com/dappforce/subsocial-parachain/blob/main/COPYRIGHT
// Full license is available at https://github.com/dappforce/subsocial-parachain/blob/main/LICENSE


//! Autogenerated weights for pallet_resource_discussions
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2024-01-05, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `benchmarks-ci`, CPU: `Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./scripts/../target/release/subsocial-collator
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet
// pallet_resource_discussions
// --extrinsic
// *
// --execution=wasm
// --wasm-execution=Compiled
// --heap-pages=4096
// --output=./pallets/resource-discussions/src/weights.rs
// --template=./.maintain/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(non_snake_case)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_resource_discussions.
pub trait WeightInfo {
    fn link_post_to_resource() -> Weight;
    fn create_resource_discussion() -> Weight;
}

/// Weights for pallet_resource_discussions using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
    /// Storage: Posts PostById (r:1 w:0)
    /// Proof Skipped: Posts PostById (max_values: None, max_size: None, mode: Measured)
    /// Storage: ResourceDiscussions ResourceDiscussion (r:0 w:1)
    /// Proof: ResourceDiscussions ResourceDiscussion (max_values: None, max_size: Some(322), added: 2797, mode: MaxEncodedLen)
    fn link_post_to_resource() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `252`
        //  Estimated: `3717`
        // Minimum execution time: 27_497_000 picoseconds.
        Weight::from_parts(28_013_000, 3717)
            .saturating_add(T::DbWeight::get().reads(1_u64))
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: ResourceDiscussions ResourceDiscussion (r:1 w:1)
    /// Proof: ResourceDiscussions ResourceDiscussion (max_values: None, max_size: Some(322), added: 2797, mode: MaxEncodedLen)
    /// Storage: Spaces SpaceById (r:1 w:0)
    /// Proof Skipped: Spaces SpaceById (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts NextPostId (r:1 w:1)
    /// Proof Skipped: Posts NextPostId (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: Timestamp Now (r:1 w:0)
    /// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    /// Storage: SpaceFollows SpaceFollowedByAccount (r:1 w:0)
    /// Proof Skipped: SpaceFollows SpaceFollowedByAccount (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts PostIdsBySpaceId (r:1 w:1)
    /// Proof Skipped: Posts PostIdsBySpaceId (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts PostById (r:0 w:1)
    /// Proof Skipped: Posts PostById (max_values: None, max_size: None, mode: Measured)
    fn create_resource_discussion() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1569`
        //  Estimated: `25005`
        // Minimum execution time: 76_102_000 picoseconds.
        Weight::from_parts(79_790_000, 25005)
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
}

// For backwards compatibility and tests
impl WeightInfo for () {
    /// Storage: Posts PostById (r:1 w:0)
    /// Proof Skipped: Posts PostById (max_values: None, max_size: None, mode: Measured)
    /// Storage: ResourceDiscussions ResourceDiscussion (r:0 w:1)
    /// Proof: ResourceDiscussions ResourceDiscussion (max_values: None, max_size: Some(322), added: 2797, mode: MaxEncodedLen)
    fn link_post_to_resource() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `252`
        //  Estimated: `3717`
        // Minimum execution time: 27_497_000 picoseconds.
        Weight::from_parts(28_013_000, 3717)
            .saturating_add(RocksDbWeight::get().reads(1_u64))
            .saturating_add(RocksDbWeight::get().writes(1_u64))
    }
    /// Storage: ResourceDiscussions ResourceDiscussion (r:1 w:1)
    /// Proof: ResourceDiscussions ResourceDiscussion (max_values: None, max_size: Some(322), added: 2797, mode: MaxEncodedLen)
    /// Storage: Spaces SpaceById (r:1 w:0)
    /// Proof Skipped: Spaces SpaceById (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts NextPostId (r:1 w:1)
    /// Proof Skipped: Posts NextPostId (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: Timestamp Now (r:1 w:0)
    /// Proof: Timestamp Now (max_values: Some(1), max_size: Some(8), added: 503, mode: MaxEncodedLen)
    /// Storage: SpaceFollows SpaceFollowedByAccount (r:1 w:0)
    /// Proof Skipped: SpaceFollows SpaceFollowedByAccount (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts PostIdsBySpaceId (r:1 w:1)
    /// Proof Skipped: Posts PostIdsBySpaceId (max_values: None, max_size: None, mode: Measured)
    /// Storage: Posts PostById (r:0 w:1)
    /// Proof Skipped: Posts PostById (max_values: None, max_size: None, mode: Measured)
    fn create_resource_discussion() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `1569`
        //  Estimated: `25005`
        // Minimum execution time: 76_102_000 picoseconds.
        Weight::from_parts(79_790_000, 25005)
            .saturating_add(RocksDbWeight::get().reads(6_u64))
            .saturating_add(RocksDbWeight::get().writes(4_u64))
    }
}