//! Autogenerated weights for pallet_roles
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-12-28, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
    // ./scripts/../target/release/subsocial-collator
    // benchmark
    // pallet
    // --chain
    // dev
    // --execution
    // wasm
    // --wasm-execution
    // Compiled
    // --pallet
    // pallet_roles
    // --extrinsic
    // *
    // --steps
    // 50
    // --repeat
    // 20
    // --heap-pages
    // 4096
    // --output
    // ./pallets/roles/src/weights.rs
    // --template
    // ./.maintain/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(non_snake_case)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_roles.
pub trait WeightInfo {
    fn create_role() -> Weight;
    fn update_role() -> Weight;
    fn delete_role(x: u32, ) -> Weight;
    fn grant_role(x: u32, ) -> Weight;
    fn revoke_role(x: u32, ) -> Weight;
}

/// Weights for pallet_roles using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
        impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: Roles NextRoleId (r:1 w:1)
            // Storage: Timestamp Now (r:1 w:0)
            // Storage: Roles RoleIdsBySpaceId (r:1 w:1)
            // Storage: Roles RoleById (r:0 w:1)
        fn create_role() -> Weight {
        (23_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
        }
            // Storage: Roles RoleById (r:1 w:1)
            // Storage: Spaces SpaceById (r:1 w:0)
        fn update_role() -> Weight {
        (19_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
            // Storage: Roles RoleById (r:1 w:1)
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: Roles UsersByRoleId (r:1 w:1)
            // Storage: Roles RoleIdsBySpaceId (r:1 w:1)
            // Storage: Roles RoleIdsByUserInSpace (r:1 w:1)
        fn delete_role(x: u32, ) -> Weight {
        (25_551_000 as Weight)
            // Standard Error: 18_000
            .saturating_add((5_581_000 as Weight).saturating_mul(x as Weight))
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(x as Weight)))
            .saturating_add(T::DbWeight::get().writes(3 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(x as Weight)))
        }
            // Storage: Roles RoleById (r:1 w:0)
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: Roles UsersByRoleId (r:1 w:1)
            // Storage: Roles RoleIdsByUserInSpace (r:1 w:1)
        fn grant_role(x: u32, ) -> Weight {
        (0 as Weight)
            // Standard Error: 127_000
            .saturating_add((17_436_000 as Weight).saturating_mul(x as Weight))
            .saturating_add(T::DbWeight::get().reads(3 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(x as Weight)))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(x as Weight)))
        }
            // Storage: Roles RoleById (r:1 w:0)
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: Roles UsersByRoleId (r:1 w:1)
            // Storage: Roles RoleIdsByUserInSpace (r:1 w:1)
        fn revoke_role(x: u32, ) -> Weight {
        (0 as Weight)
            // Standard Error: 16_000
            .saturating_add((6_606_000 as Weight).saturating_mul(x as Weight))
            .saturating_add(T::DbWeight::get().reads(3 as Weight))
            .saturating_add(T::DbWeight::get().reads((1 as Weight).saturating_mul(x as Weight)))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
            .saturating_add(T::DbWeight::get().writes((1 as Weight).saturating_mul(x as Weight)))
        }
    }

    // For backwards compatibility and tests
    impl WeightInfo for () {
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: Roles NextRoleId (r:1 w:1)
            // Storage: Timestamp Now (r:1 w:0)
            // Storage: Roles RoleIdsBySpaceId (r:1 w:1)
            // Storage: Roles RoleById (r:0 w:1)
        fn create_role() -> Weight {
        (23_000_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
        }
            // Storage: Roles RoleById (r:1 w:1)
            // Storage: Spaces SpaceById (r:1 w:0)
        fn update_role() -> Weight {
        (19_000_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
            // Storage: Roles RoleById (r:1 w:1)
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: Roles UsersByRoleId (r:1 w:1)
            // Storage: Roles RoleIdsBySpaceId (r:1 w:1)
            // Storage: Roles RoleIdsByUserInSpace (r:1 w:1)
        fn delete_role(x: u32, ) -> Weight {
        (25_551_000 as Weight)
            // Standard Error: 18_000
            .saturating_add((5_581_000 as Weight).saturating_mul(x as Weight))
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(x as Weight)))
            .saturating_add(RocksDbWeight::get().writes(3 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(x as Weight)))
        }
            // Storage: Roles RoleById (r:1 w:0)
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: Roles UsersByRoleId (r:1 w:1)
            // Storage: Roles RoleIdsByUserInSpace (r:1 w:1)
        fn grant_role(x: u32, ) -> Weight {
        (0 as Weight)
            // Standard Error: 127_000
            .saturating_add((17_436_000 as Weight).saturating_mul(x as Weight))
            .saturating_add(RocksDbWeight::get().reads(3 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(x as Weight)))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(x as Weight)))
        }
            // Storage: Roles RoleById (r:1 w:0)
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: Roles UsersByRoleId (r:1 w:1)
            // Storage: Roles RoleIdsByUserInSpace (r:1 w:1)
        fn revoke_role(x: u32, ) -> Weight {
        (0 as Weight)
            // Standard Error: 16_000
            .saturating_add((6_606_000 as Weight).saturating_mul(x as Weight))
            .saturating_add(RocksDbWeight::get().reads(3 as Weight))
            .saturating_add(RocksDbWeight::get().reads((1 as Weight).saturating_mul(x as Weight)))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
            .saturating_add(RocksDbWeight::get().writes((1 as Weight).saturating_mul(x as Weight)))
        }
    }
