
//! Autogenerated weights for pallet_roles
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-02-14, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
    // ./scripts/../target/release/subsocial-collator
    // benchmark
    // pallet
    // --chain
    // dev
    // --execution
    // wasm
    // --wasm-execution
    // Compiled
    // --pallet
    // pallet_roles
    // --extrinsic
    // *
    // --steps
    // 50
    // --repeat
    // 20
    // --heap-pages
    // 4096
    // --output
    // pallets/roles/src/weights.rs
    // --template
    // ./.maintain/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(non_snake_case)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_roles.
pub trait WeightInfo {
    fn create_role() -> Weight;
    fn update_role() -> Weight;
    fn delete_role(x: u32, ) -> Weight;
    fn grant_role(x: u32, ) -> Weight;
    fn revoke_role(x: u32, ) -> Weight;
}

/// Weights for pallet_roles using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
        impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: Roles NextRoleId (r:1 w:1)
            // Storage: Timestamp Now (r:1 w:0)
            // Storage: Roles RoleIdsBySpaceId (r:1 w:1)
            // Storage: Roles RoleById (r:0 w:1)
        fn create_role() -> Weight {
        // Minimum execution time: 29_000 nanoseconds.
        Weight::from_ref_time(46_007_000)
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().writes(3))
        }
            // Storage: Roles RoleById (r:1 w:1)
            // Storage: Spaces SpaceById (r:1 w:0)
        fn update_role() -> Weight {
        // Minimum execution time: 26_000 nanoseconds.
        Weight::from_ref_time(39_597_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
        }
            // Storage: Roles RoleById (r:1 w:1)
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: Roles UsersByRoleId (r:1 w:1)
            // Storage: Roles RoleIdsBySpaceId (r:1 w:1)
            // Storage: Roles RoleIdsByUserInSpace (r:1 w:1)
            /// The range of component `x` is `[0, 40]`.
        fn delete_role(x: u32, ) -> Weight {
        // Minimum execution time: 32_000 nanoseconds.
        Weight::from_ref_time(51_749_000)
            // Standard Error: 4_403
            .saturating_add(Weight::from_ref_time(5_304_109).saturating_mul(x.into()))
            .saturating_add(T::DbWeight::get().reads(4))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(x.into())))
            .saturating_add(T::DbWeight::get().writes(3))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(x.into())))
        }
            // Storage: Roles RoleById (r:1 w:0)
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: Roles UsersByRoleId (r:1 w:1)
            // Storage: Roles RoleIdsByUserInSpace (r:1 w:1)
            /// The range of component `x` is `[1, 500]`.
        fn grant_role(x: u32, ) -> Weight {
        // Minimum execution time: 31_000 nanoseconds.
        Weight::from_ref_time(0)
            // Standard Error: 112_799
            .saturating_add(Weight::from_ref_time(16_191_263).saturating_mul(x.into()))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(x.into())))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(x.into())))
        }
            // Storage: Roles RoleById (r:1 w:0)
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: Roles UsersByRoleId (r:1 w:1)
            // Storage: Roles RoleIdsByUserInSpace (r:1 w:1)
            /// The range of component `x` is `[1, 500]`.
        fn revoke_role(x: u32, ) -> Weight {
        // Minimum execution time: 33_000 nanoseconds.
        Weight::from_ref_time(0)
            // Standard Error: 9_186
            .saturating_add(Weight::from_ref_time(5_884_308).saturating_mul(x.into()))
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().reads((1_u64).saturating_mul(x.into())))
            .saturating_add(T::DbWeight::get().writes(1))
            .saturating_add(T::DbWeight::get().writes((1_u64).saturating_mul(x.into())))
        }
    }

    // For backwards compatibility and tests
    impl WeightInfo for () {
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: Roles NextRoleId (r:1 w:1)
            // Storage: Timestamp Now (r:1 w:0)
            // Storage: Roles RoleIdsBySpaceId (r:1 w:1)
            // Storage: Roles RoleById (r:0 w:1)
        fn create_role() -> Weight {
        // Minimum execution time: 29_000 nanoseconds.
        Weight::from_ref_time(46_007_000)
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().writes(3))
        }
            // Storage: Roles RoleById (r:1 w:1)
            // Storage: Spaces SpaceById (r:1 w:0)
        fn update_role() -> Weight {
        // Minimum execution time: 26_000 nanoseconds.
        Weight::from_ref_time(39_597_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
        }
            // Storage: Roles RoleById (r:1 w:1)
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: Roles UsersByRoleId (r:1 w:1)
            // Storage: Roles RoleIdsBySpaceId (r:1 w:1)
            // Storage: Roles RoleIdsByUserInSpace (r:1 w:1)
            /// The range of component `x` is `[0, 40]`.
        fn delete_role(x: u32, ) -> Weight {
        // Minimum execution time: 32_000 nanoseconds.
        Weight::from_ref_time(51_749_000)
            // Standard Error: 4_403
            .saturating_add(Weight::from_ref_time(5_304_109).saturating_mul(x.into()))
            .saturating_add(RocksDbWeight::get().reads(4))
            .saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(x.into())))
            .saturating_add(RocksDbWeight::get().writes(3))
            .saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(x.into())))
        }
            // Storage: Roles RoleById (r:1 w:0)
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: Roles UsersByRoleId (r:1 w:1)
            // Storage: Roles RoleIdsByUserInSpace (r:1 w:1)
            /// The range of component `x` is `[1, 500]`.
        fn grant_role(x: u32, ) -> Weight {
        // Minimum execution time: 31_000 nanoseconds.
        Weight::from_ref_time(0)
            // Standard Error: 112_799
            .saturating_add(Weight::from_ref_time(16_191_263).saturating_mul(x.into()))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(x.into())))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(x.into())))
        }
            // Storage: Roles RoleById (r:1 w:0)
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: Roles UsersByRoleId (r:1 w:1)
            // Storage: Roles RoleIdsByUserInSpace (r:1 w:1)
            /// The range of component `x` is `[1, 500]`.
        fn revoke_role(x: u32, ) -> Weight {
        // Minimum execution time: 33_000 nanoseconds.
        Weight::from_ref_time(0)
            // Standard Error: 9_186
            .saturating_add(Weight::from_ref_time(5_884_308).saturating_mul(x.into()))
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().reads((1_u64).saturating_mul(x.into())))
            .saturating_add(RocksDbWeight::get().writes(1))
            .saturating_add(RocksDbWeight::get().writes((1_u64).saturating_mul(x.into())))
        }
    }
