// Copyright (C) DAPPFORCE PTE. LTD.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0.
//
// Full notice is available at https://github.com/dappforce/subsocial-parachain/blob/main/COPYRIGHT
// Full license is available at https://github.com/dappforce/subsocial-parachain/blob/main/LICENSE

//! Autogenerated weights for `pallet_xcm`
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-02-23, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `bm6`, CPU: `Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("statemint-dev"), DB CACHE: 1024

// Executed Command:
// ./artifacts/polkadot-parachain
// benchmark
// pallet
// --chain=statemint-dev
// --execution=wasm
// --wasm-execution=compiled
// --pallet=pallet_xcm
// --extrinsic=*
// --steps=50
// --repeat=20
// --json
// --header=./file_header.txt
// --output=./parachains/runtimes/assets/statemint/src/weights/pallet_xcm.rs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::Weight};
use sp_std::marker::PhantomData;

/// Weight functions for `pallet_xcm`.
pub struct WeightInfo<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_xcm::WeightInfo for WeightInfo<T> {
    /// Storage: PolkadotXcm SupportedVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
    /// Storage: PolkadotXcm VersionDiscoveryQueue (r:1 w:1)
    /// Proof Skipped: PolkadotXcm VersionDiscoveryQueue (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: PolkadotXcm SafeXcmVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SafeXcmVersion (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem HostConfiguration (r:1 w:0)
    /// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
    /// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
    fn send() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `38`
        //  Estimated: `9595`
        // Minimum execution time: 42_333_000 picoseconds.
        Weight::from_parts(42_911_000, 9595)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: Benchmark Override (r:0 w:0)
    /// Proof Skipped: Benchmark Override (max_values: None, max_size: None, mode: Measured)
    fn teleport_assets() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 18_446_744_073_709_551_000 picoseconds.
        Weight::from_parts(18_446_744_073_709_551_000, 0)
    }
    /// Storage: Benchmark Override (r:0 w:0)
    /// Proof Skipped: Benchmark Override (max_values: None, max_size: None, mode: Measured)
    fn reserve_transfer_assets() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 18_446_744_073_709_551_000 picoseconds.
        Weight::from_parts(18_446_744_073_709_551_000, 0)
    }
    /// Storage: Benchmark Override (r:0 w:0)
    /// Proof Skipped: Benchmark Override (max_values: None, max_size: None, mode: Measured)
    fn execute() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 18_446_744_073_709_551_000 picoseconds.
        Weight::from_parts(18_446_744_073_709_551_000, 0)
    }
    /// Storage: PolkadotXcm SupportedVersion (r:0 w:1)
    /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
    fn force_xcm_version() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 16_078_000 picoseconds.
        Weight::from_parts(16_381_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: PolkadotXcm SafeXcmVersion (r:0 w:1)
    /// Proof Skipped: PolkadotXcm SafeXcmVersion (max_values: Some(1), max_size: None, mode: Measured)
    fn force_default_xcm_version() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_218_000 picoseconds.
        Weight::from_parts(5_430_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: PolkadotXcm VersionNotifiers (r:1 w:1)
    /// Proof Skipped: PolkadotXcm VersionNotifiers (max_values: None, max_size: None, mode: Measured)
    /// Storage: PolkadotXcm QueryCounter (r:1 w:1)
    /// Proof Skipped: PolkadotXcm QueryCounter (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: PolkadotXcm SupportedVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
    /// Storage: PolkadotXcm VersionDiscoveryQueue (r:1 w:1)
    /// Proof Skipped: PolkadotXcm VersionDiscoveryQueue (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: PolkadotXcm SafeXcmVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SafeXcmVersion (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem HostConfiguration (r:1 w:0)
    /// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
    /// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: PolkadotXcm Queries (r:0 w:1)
    /// Proof Skipped: PolkadotXcm Queries (max_values: None, max_size: None, mode: Measured)
    fn force_subscribe_version_notify() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `38`
        //  Estimated: `14659`
        // Minimum execution time: 50_095_000 picoseconds.
        Weight::from_parts(50_860_000, 14659)
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
    /// Storage: PolkadotXcm VersionNotifiers (r:1 w:1)
    /// Proof Skipped: PolkadotXcm VersionNotifiers (max_values: None, max_size: None, mode: Measured)
    /// Storage: PolkadotXcm SupportedVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
    /// Storage: PolkadotXcm VersionDiscoveryQueue (r:1 w:1)
    /// Proof Skipped: PolkadotXcm VersionDiscoveryQueue (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: PolkadotXcm SafeXcmVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SafeXcmVersion (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem HostConfiguration (r:1 w:0)
    /// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
    /// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: PolkadotXcm Queries (r:0 w:1)
    /// Proof Skipped: PolkadotXcm Queries (max_values: None, max_size: None, mode: Measured)
    fn force_unsubscribe_version_notify() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `220`
        //  Estimated: `14410`
        // Minimum execution time: 49_522_000 picoseconds.
        Weight::from_parts(50_493_000, 14410)
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: PolkadotXcm SupportedVersion (r:4 w:2)
    /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
    fn migrate_supported_version() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `165`
        //  Estimated: `11055`
        // Minimum execution time: 24_963_000 picoseconds.
        Weight::from_parts(25_293_000, 11055)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: PolkadotXcm VersionNotifiers (r:4 w:2)
    /// Proof Skipped: PolkadotXcm VersionNotifiers (max_values: None, max_size: None, mode: Measured)
    fn migrate_version_notifiers() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `169`
        //  Estimated: `11059`
        // Minimum execution time: 24_996_000 picoseconds.
        Weight::from_parts(25_432_000, 11059)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: PolkadotXcm VersionNotifyTargets (r:5 w:0)
    /// Proof Skipped: PolkadotXcm VersionNotifyTargets (max_values: None, max_size: None, mode: Measured)
    fn already_notified_target() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `176`
        //  Estimated: `13541`
        // Minimum execution time: 26_093_000 picoseconds.
        Weight::from_parts(26_769_000, 13541)
            .saturating_add(T::DbWeight::get().reads(5_u64))
    }
    /// Storage: PolkadotXcm VersionNotifyTargets (r:2 w:1)
    /// Proof Skipped: PolkadotXcm VersionNotifyTargets (max_values: None, max_size: None, mode: Measured)
    /// Storage: PolkadotXcm SupportedVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
    /// Storage: PolkadotXcm VersionDiscoveryQueue (r:1 w:1)
    /// Proof Skipped: PolkadotXcm VersionDiscoveryQueue (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: PolkadotXcm SafeXcmVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SafeXcmVersion (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem HostConfiguration (r:1 w:0)
    /// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
    /// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
    fn notify_current_targets() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `106`
        //  Estimated: `15981`
        // Minimum execution time: 45_586_000 picoseconds.
        Weight::from_parts(46_009_000, 15981)
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: PolkadotXcm VersionNotifyTargets (r:3 w:0)
    /// Proof Skipped: PolkadotXcm VersionNotifyTargets (max_values: None, max_size: None, mode: Measured)
    fn notify_target_migration_fail() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `136`
        //  Estimated: `8551`
        // Minimum execution time: 13_674_000 picoseconds.
        Weight::from_parts(14_109_000, 8551)
            .saturating_add(T::DbWeight::get().reads(3_u64))
    }
    /// Storage: PolkadotXcm VersionNotifyTargets (r:4 w:2)
    /// Proof Skipped: PolkadotXcm VersionNotifyTargets (max_values: None, max_size: None, mode: Measured)
    fn migrate_version_notify_targets() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `176`
        //  Estimated: `11066`
        // Minimum execution time: 25_564_000 picoseconds.
        Weight::from_parts(26_152_000, 11066)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: PolkadotXcm VersionNotifyTargets (r:4 w:2)
    /// Proof Skipped: PolkadotXcm VersionNotifyTargets (max_values: None, max_size: None, mode: Measured)
    /// Storage: PolkadotXcm SupportedVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
    /// Storage: PolkadotXcm VersionDiscoveryQueue (r:1 w:1)
    /// Proof Skipped: PolkadotXcm VersionDiscoveryQueue (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: PolkadotXcm SafeXcmVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SafeXcmVersion (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem HostConfiguration (r:1 w:0)
    /// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
    /// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
    fn migrate_and_notify_old_targets() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `182`
        //  Estimated: `21387`
        // Minimum execution time: 55_811_000 picoseconds.
        Weight::from_parts(56_748_000, 21387)
            .saturating_add(T::DbWeight::get().reads(9_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
}
