
//! Autogenerated weights for pallet_xcm
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-11-28, STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `1000000`
//! HOSTNAME: `benchmarks-ci`, CPU: `Intel(R) Xeon(R) Platinum 8358 CPU @ 2.60GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./scripts/../target/release/subsocial-collator
// benchmark
// pallet
// --chain=dev
// --steps=50
// --repeat=20
// --pallet=pallet_xcm
// --extrinsic=*
// --execution=wasm
// --wasm-execution=Compiled
// --heap-pages=4096
// --output=./runtime/src/weights/pallet_xcm.rs
// --template=.maintain/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(non_snake_case)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weights for pallet_xcm using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> pallet_xcm::WeightInfo for SubstrateWeight<T> {
    /// Storage: PolkadotXcm SupportedVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
    /// Storage: PolkadotXcm VersionDiscoveryQueue (r:1 w:1)
    /// Proof Skipped: PolkadotXcm VersionDiscoveryQueue (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: PolkadotXcm SafeXcmVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SafeXcmVersion (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem HostConfiguration (r:1 w:0)
    /// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
    /// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
    fn send() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `38`
        //  Estimated: `9595`
        // Minimum execution time: 44_258_000 picoseconds.
        Weight::from_parts(46_634_000, 9595)
            .saturating_add(T::DbWeight::get().reads(5_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: Benchmark Override (r:0 w:0)
    /// Proof Skipped: Benchmark Override (max_values: None, max_size: None, mode: Measured)
    fn teleport_assets() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 18_446_744_073_709_551_000 picoseconds.
        Weight::from_parts(18_446_744_073_709_551_000, 0)
    }
    /// Storage: ParachainInfo ParachainId (r:1 w:0)
    /// Proof: ParachainInfo ParachainId (max_values: Some(1), max_size: Some(4), added: 499, mode: MaxEncodedLen)
    fn reserve_transfer_assets() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `69`
        //  Estimated: `1489`
        // Minimum execution time: 37_190_000 picoseconds.
        Weight::from_parts(38_199_000, 1489)
            .saturating_add(T::DbWeight::get().reads(1_u64))
    }
    /// Storage: Benchmark Override (r:0 w:0)
    /// Proof Skipped: Benchmark Override (max_values: None, max_size: None, mode: Measured)
    fn execute() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 18_446_744_073_709_551_000 picoseconds.
        Weight::from_parts(18_446_744_073_709_551_000, 0)
    }
    /// Storage: PolkadotXcm SupportedVersion (r:0 w:1)
    /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
    fn force_xcm_version() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 16_593_000 picoseconds.
        Weight::from_parts(17_052_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: PolkadotXcm SafeXcmVersion (r:0 w:1)
    /// Proof Skipped: PolkadotXcm SafeXcmVersion (max_values: Some(1), max_size: None, mode: Measured)
    fn force_default_xcm_version() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `0`
        //  Estimated: `0`
        // Minimum execution time: 5_283_000 picoseconds.
        Weight::from_parts(5_647_000, 0)
            .saturating_add(T::DbWeight::get().writes(1_u64))
    }
    /// Storage: PolkadotXcm VersionNotifiers (r:1 w:1)
    /// Proof Skipped: PolkadotXcm VersionNotifiers (max_values: None, max_size: None, mode: Measured)
    /// Storage: PolkadotXcm QueryCounter (r:1 w:1)
    /// Proof Skipped: PolkadotXcm QueryCounter (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: PolkadotXcm SupportedVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
    /// Storage: PolkadotXcm VersionDiscoveryQueue (r:1 w:1)
    /// Proof Skipped: PolkadotXcm VersionDiscoveryQueue (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: PolkadotXcm SafeXcmVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SafeXcmVersion (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem HostConfiguration (r:1 w:0)
    /// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
    /// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: PolkadotXcm Queries (r:0 w:1)
    /// Proof Skipped: PolkadotXcm Queries (max_values: None, max_size: None, mode: Measured)
    fn force_subscribe_version_notify() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `38`
        //  Estimated: `14659`
        // Minimum execution time: 51_994_000 picoseconds.
        Weight::from_parts(55_330_000, 14659)
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(5_u64))
    }
    /// Storage: PolkadotXcm VersionNotifiers (r:1 w:1)
    /// Proof Skipped: PolkadotXcm VersionNotifiers (max_values: None, max_size: None, mode: Measured)
    /// Storage: PolkadotXcm SupportedVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
    /// Storage: PolkadotXcm VersionDiscoveryQueue (r:1 w:1)
    /// Proof Skipped: PolkadotXcm VersionDiscoveryQueue (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: PolkadotXcm SafeXcmVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SafeXcmVersion (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem HostConfiguration (r:1 w:0)
    /// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
    /// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: PolkadotXcm Queries (r:0 w:1)
    /// Proof Skipped: PolkadotXcm Queries (max_values: None, max_size: None, mode: Measured)
    fn force_unsubscribe_version_notify() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `220`
        //  Estimated: `14410`
        // Minimum execution time: 52_662_000 picoseconds.
        Weight::from_parts(64_100_000, 14410)
            .saturating_add(T::DbWeight::get().reads(6_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
    /// Storage: PolkadotXcm SupportedVersion (r:4 w:2)
    /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
    fn migrate_supported_version() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `165`
        //  Estimated: `11055`
        // Minimum execution time: 25_567_000 picoseconds.
        Weight::from_parts(29_935_000, 11055)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: PolkadotXcm VersionNotifiers (r:4 w:2)
    /// Proof Skipped: PolkadotXcm VersionNotifiers (max_values: None, max_size: None, mode: Measured)
    fn migrate_version_notifiers() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `169`
        //  Estimated: `11059`
        // Minimum execution time: 25_583_000 picoseconds.
        Weight::from_parts(26_458_000, 11059)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: PolkadotXcm VersionNotifyTargets (r:5 w:0)
    /// Proof Skipped: PolkadotXcm VersionNotifyTargets (max_values: None, max_size: None, mode: Measured)
    fn already_notified_target() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `176`
        //  Estimated: `13541`
        // Minimum execution time: 25_999_000 picoseconds.
        Weight::from_parts(26_996_000, 13541)
            .saturating_add(T::DbWeight::get().reads(5_u64))
    }
    /// Storage: PolkadotXcm VersionNotifyTargets (r:2 w:1)
    /// Proof Skipped: PolkadotXcm VersionNotifyTargets (max_values: None, max_size: None, mode: Measured)
    /// Storage: PolkadotXcm SupportedVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
    /// Storage: PolkadotXcm VersionDiscoveryQueue (r:1 w:1)
    /// Proof Skipped: PolkadotXcm VersionDiscoveryQueue (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: PolkadotXcm SafeXcmVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SafeXcmVersion (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem HostConfiguration (r:1 w:0)
    /// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
    /// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
    fn notify_current_targets() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `106`
        //  Estimated: `15981`
        // Minimum execution time: 46_717_000 picoseconds.
        Weight::from_parts(49_024_000, 15981)
            .saturating_add(T::DbWeight::get().reads(7_u64))
            .saturating_add(T::DbWeight::get().writes(3_u64))
    }
    /// Storage: PolkadotXcm VersionNotifyTargets (r:3 w:0)
    /// Proof Skipped: PolkadotXcm VersionNotifyTargets (max_values: None, max_size: None, mode: Measured)
    fn notify_target_migration_fail() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `136`
        //  Estimated: `8551`
        // Minimum execution time: 13_867_000 picoseconds.
        Weight::from_parts(14_344_000, 8551)
            .saturating_add(T::DbWeight::get().reads(3_u64))
    }
    /// Storage: PolkadotXcm VersionNotifyTargets (r:4 w:2)
    /// Proof Skipped: PolkadotXcm VersionNotifyTargets (max_values: None, max_size: None, mode: Measured)
    fn migrate_version_notify_targets() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `176`
        //  Estimated: `11066`
        // Minimum execution time: 25_575_000 picoseconds.
        Weight::from_parts(26_708_000, 11066)
            .saturating_add(T::DbWeight::get().reads(4_u64))
            .saturating_add(T::DbWeight::get().writes(2_u64))
    }
    /// Storage: PolkadotXcm VersionNotifyTargets (r:4 w:2)
    /// Proof Skipped: PolkadotXcm VersionNotifyTargets (max_values: None, max_size: None, mode: Measured)
    /// Storage: PolkadotXcm SupportedVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SupportedVersion (max_values: None, max_size: None, mode: Measured)
    /// Storage: PolkadotXcm VersionDiscoveryQueue (r:1 w:1)
    /// Proof Skipped: PolkadotXcm VersionDiscoveryQueue (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: PolkadotXcm SafeXcmVersion (r:1 w:0)
    /// Proof Skipped: PolkadotXcm SafeXcmVersion (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem HostConfiguration (r:1 w:0)
    /// Proof Skipped: ParachainSystem HostConfiguration (max_values: Some(1), max_size: None, mode: Measured)
    /// Storage: ParachainSystem PendingUpwardMessages (r:1 w:1)
    /// Proof Skipped: ParachainSystem PendingUpwardMessages (max_values: Some(1), max_size: None, mode: Measured)
    fn migrate_and_notify_old_targets() -> Weight {
        // Proof Size summary in bytes:
        //  Measured:  `182`
        //  Estimated: `21387`
        // Minimum execution time: 56_742_000 picoseconds.
        Weight::from_parts(58_978_000, 21387)
            .saturating_add(T::DbWeight::get().reads(9_u64))
            .saturating_add(T::DbWeight::get().writes(4_u64))
    }
}
