//! Autogenerated weights for pallet_space_ownership
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2022-12-20, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
    // ./scripts/../target/release/subsocial-collator
    // benchmark
    // pallet
    // --chain
    // dev
    // --execution
    // wasm
    // --wasm-execution
    // Compiled
    // --pallet
    // pallet_space_ownership
    // --extrinsic
    // *
    // --steps
    // 50
    // --repeat
    // 20
    // --heap-pages
    // 4096
    // --output
    // ./pallets/space-ownership/src/weights.rs
    // --template
    // ./.maintain/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_space_ownership.
pub trait WeightInfo {
    fn transfer_space_ownership() -> Weight;
    fn accept_pending_ownership() -> Weight;
    fn reject_pending_ownership() -> Weight;
}

/// Weights for pallet_space_ownership using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
        impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: SpaceOwnership PendingSpaceOwner (r:0 w:1)
        fn transfer_space_ownership() -> Weight {
        (14_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(1 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
            // Storage: Spaces SpaceById (r:1 w:1)
            // Storage: SpaceOwnership PendingSpaceOwner (r:1 w:1)
            // Storage: Spaces SpaceIdsByOwner (r:2 w:2)
        fn accept_pending_ownership() -> Weight {
        (24_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(4 as Weight))
            .saturating_add(T::DbWeight::get().writes(4 as Weight))
        }
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: SpaceOwnership PendingSpaceOwner (r:1 w:1)
        fn reject_pending_ownership() -> Weight {
        (16_000_000 as Weight)
            .saturating_add(T::DbWeight::get().reads(2 as Weight))
            .saturating_add(T::DbWeight::get().writes(1 as Weight))
        }
    }

    // For backwards compatibility and tests
    impl WeightInfo for () {
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: SpaceOwnership PendingSpaceOwner (r:0 w:1)
        fn transfer_space_ownership() -> Weight {
        (14_000_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(1 as Weight))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
            // Storage: Spaces SpaceById (r:1 w:1)
            // Storage: SpaceOwnership PendingSpaceOwner (r:1 w:1)
            // Storage: Spaces SpaceIdsByOwner (r:2 w:2)
        fn accept_pending_ownership() -> Weight {
        (24_000_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(4 as Weight))
            .saturating_add(RocksDbWeight::get().writes(4 as Weight))
        }
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: SpaceOwnership PendingSpaceOwner (r:1 w:1)
        fn reject_pending_ownership() -> Weight {
        (16_000_000 as Weight)
            .saturating_add(RocksDbWeight::get().reads(2 as Weight))
            .saturating_add(RocksDbWeight::get().writes(1 as Weight))
        }
    }
