// Copyright (C) DAPPFORCE PTE. LTD., dappforce@gmail.com.
// SPDX-License-Identifier: GPL-3.0-or-later WITH Classpath-exception-2.0.

// Full notice is available at https://github.com/dappforce/subsocial-parachain/blob/main/HEADER-GPL3. 
// Full license is available at https://github.com/dappforce/subsocial-parachain/blob/main/LICENSE.


//! Autogenerated weights for pallet_space_ownership
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-02-15, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! HOSTNAME: `benchmarks-ci`, CPU: `Intel(R) Xeon(R) Platinum 8280 CPU @ 2.70GHz`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
    // ./scripts/../target/release/subsocial-collator
    // benchmark
    // pallet
    // --chain
    // dev
    // --execution
    // wasm
    // --wasm-execution
    // Compiled
    // --pallet
    // pallet_space_ownership
    // --extrinsic
    // *
    // --steps
    // 50
    // --repeat
    // 20
    // --heap-pages
    // 4096
    // --output
    // pallets/space-ownership/src/weights.rs
    // --template
    // ./.maintain/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(non_snake_case)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_space_ownership.
pub trait WeightInfo {
    fn transfer_space_ownership() -> Weight;
    fn accept_pending_ownership() -> Weight;
    fn reject_pending_ownership() -> Weight;
}

/// Weights for pallet_space_ownership using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
        impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: SpaceOwnership PendingSpaceOwner (r:0 w:1)
        fn transfer_space_ownership() -> Weight {
        // Minimum execution time: 36_442 nanoseconds.
        Weight::from_ref_time(36_970_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
        }
            // Storage: Spaces SpaceById (r:1 w:1)
            // Storage: SpaceOwnership PendingSpaceOwner (r:1 w:1)
            // Storage: Spaces SpaceIdsByOwner (r:2 w:2)
            // Storage: Profiles ProfileSpaceIdByAccount (r:1 w:0)
        fn accept_pending_ownership() -> Weight {
        // Minimum execution time: 60_105 nanoseconds.
        Weight::from_ref_time(60_893_000)
            .saturating_add(T::DbWeight::get().reads(5))
            .saturating_add(T::DbWeight::get().writes(4))
        }
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: SpaceOwnership PendingSpaceOwner (r:1 w:1)
        fn reject_pending_ownership() -> Weight {
        // Minimum execution time: 40_600 nanoseconds.
        Weight::from_ref_time(41_309_000)
            .saturating_add(T::DbWeight::get().reads(2))
            .saturating_add(T::DbWeight::get().writes(1))
        }
    }

    // For backwards compatibility and tests
    impl WeightInfo for () {
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: SpaceOwnership PendingSpaceOwner (r:0 w:1)
        fn transfer_space_ownership() -> Weight {
        // Minimum execution time: 36_442 nanoseconds.
        Weight::from_ref_time(36_970_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
        }
            // Storage: Spaces SpaceById (r:1 w:1)
            // Storage: SpaceOwnership PendingSpaceOwner (r:1 w:1)
            // Storage: Spaces SpaceIdsByOwner (r:2 w:2)
            // Storage: Profiles ProfileSpaceIdByAccount (r:1 w:0)
        fn accept_pending_ownership() -> Weight {
        // Minimum execution time: 60_105 nanoseconds.
        Weight::from_ref_time(60_893_000)
            .saturating_add(RocksDbWeight::get().reads(5))
            .saturating_add(RocksDbWeight::get().writes(4))
        }
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: SpaceOwnership PendingSpaceOwner (r:1 w:1)
        fn reject_pending_ownership() -> Weight {
        // Minimum execution time: 40_600 nanoseconds.
        Weight::from_ref_time(41_309_000)
            .saturating_add(RocksDbWeight::get().reads(2))
            .saturating_add(RocksDbWeight::get().writes(1))
        }
    }
