
//! Autogenerated weights for pallet_profiles
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: 2023-02-14, STEPS: `50`, REPEAT: 20, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
    // ./scripts/../target/release/subsocial-collator
    // benchmark
    // pallet
    // --chain
    // dev
    // --execution
    // wasm
    // --wasm-execution
    // Compiled
    // --pallet
    // pallet_profiles
    // --extrinsic
    // *
    // --steps
    // 50
    // --repeat
    // 20
    // --heap-pages
    // 4096
    // --output
    // pallets/profiles/src/weights.rs
    // --template
    // ./.maintain/weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(non_snake_case)]

use frame_support::{traits::Get, weights::{Weight, constants::RocksDbWeight}};
use sp_std::marker::PhantomData;

/// Weight functions needed for pallet_profiles.
pub trait WeightInfo {
    fn set_profile() -> Weight;
    fn reset_profile() -> Weight;
    fn create_space_as_profile() -> Weight;
}

/// Weights for pallet_profiles using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
        impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: Profiles ProfileSpaceIdByAccount (r:0 w:1)
        fn set_profile() -> Weight {
        // Minimum execution time: 20_000 nanoseconds.
        Weight::from_ref_time(25_517_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
        }
            // Storage: Profiles ProfileSpaceIdByAccount (r:1 w:1)
        fn reset_profile() -> Weight {
        // Minimum execution time: 18_000 nanoseconds.
        Weight::from_ref_time(22_806_000)
            .saturating_add(T::DbWeight::get().reads(1))
            .saturating_add(T::DbWeight::get().writes(1))
        }
            // Storage: Spaces SpaceIdsByOwner (r:1 w:1)
            // Storage: Spaces NextSpaceId (r:1 w:1)
            // Storage: Timestamp Now (r:1 w:0)
            // Storage: Profiles ProfileSpaceIdByAccount (r:0 w:1)
            // Storage: Spaces SpaceById (r:0 w:1)
        fn create_space_as_profile() -> Weight {
        // Minimum execution time: 28_000 nanoseconds.
        Weight::from_ref_time(42_500_000)
            .saturating_add(T::DbWeight::get().reads(3))
            .saturating_add(T::DbWeight::get().writes(4))
        }
    }

    // For backwards compatibility and tests
    impl WeightInfo for () {
            // Storage: Spaces SpaceById (r:1 w:0)
            // Storage: Profiles ProfileSpaceIdByAccount (r:0 w:1)
        fn set_profile() -> Weight {
        // Minimum execution time: 20_000 nanoseconds.
        Weight::from_ref_time(25_517_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
        }
            // Storage: Profiles ProfileSpaceIdByAccount (r:1 w:1)
        fn reset_profile() -> Weight {
        // Minimum execution time: 18_000 nanoseconds.
        Weight::from_ref_time(22_806_000)
            .saturating_add(RocksDbWeight::get().reads(1))
            .saturating_add(RocksDbWeight::get().writes(1))
        }
            // Storage: Spaces SpaceIdsByOwner (r:1 w:1)
            // Storage: Spaces NextSpaceId (r:1 w:1)
            // Storage: Timestamp Now (r:1 w:0)
            // Storage: Profiles ProfileSpaceIdByAccount (r:0 w:1)
            // Storage: Spaces SpaceById (r:0 w:1)
        fn create_space_as_profile() -> Weight {
        // Minimum execution time: 28_000 nanoseconds.
        Weight::from_ref_time(42_500_000)
            .saturating_add(RocksDbWeight::get().reads(3))
            .saturating_add(RocksDbWeight::get().writes(4))
        }
    }
