name: Check and Test Code

on:
  pull_request:
  push:
    branches: [ "main", "feature/*" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test-code:
    runs-on: public-runners

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install build tools
        run: ./scripts/init.sh

      - name: Cache Dependencies
        uses: Swatinem/rust-cache@v1

      - name: Check Code
        run: cargo check --release

      - name: Test Code
        run: cargo test
